// <auto-generated />
using System;
using System.Net;
using Finans.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finans.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinansDbContext))]
    [Migration("20260719224508_LessonSectionFigureKey")]
    partial class LessonSectionFigureKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finans.Domain.Education.ConceptTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ConceptTags", (string)null);
                });

            modelBuilder.Entity("Finans.Domain.Education.LearningTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("LearningTracks", null, t =>
                        {
                            t.HasCheckConstraint("CK_LearningTracks_Level", "\"Level\" IN ('Beginner', 'Intermediate', 'Advanced')");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Education.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TrackId", "OrderIndex");

                    b.ToTable("Lessons", null, t =>
                        {
                            t.HasCheckConstraint("CK_Lessons_EstimatedMinutes", "\"EstimatedMinutes\" > 0");

                            t.HasCheckConstraint("CK_Lessons_Level", "\"Level\" IN ('Beginner', 'Intermediate', 'Advanced')");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Education.LessonConceptTag", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConceptTagId")
                        .HasColumnType("uuid");

                    b.HasKey("LessonId", "ConceptTagId");

                    b.HasIndex("ConceptTagId");

                    b.ToTable("LessonConceptTags", (string)null);
                });

            modelBuilder.Entity("Finans.Domain.Education.LessonPrerequisite", b =>
                {
                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrerequisiteLessonId")
                        .HasColumnType("uuid");

                    b.HasKey("LessonId", "PrerequisiteLessonId");

                    b.HasIndex("PrerequisiteLessonId");

                    b.ToTable("LessonPrerequisites", null, t =>
                        {
                            t.HasCheckConstraint("CK_LessonPrerequisites_NoSelf", "\"LessonId\" <> \"PrerequisiteLessonId\"");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Education.LessonSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DepthTier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FigureKey")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Heading")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "DepthTier");

                    b.HasIndex("LessonId", "OrderIndex");

                    b.ToTable("LessonSections", null, t =>
                        {
                            t.HasCheckConstraint("CK_LessonSections_DepthTier", "\"DepthTier\" IN ('Core', 'Context', 'Deep')");

                            t.HasCheckConstraint("CK_LessonSections_Kind", "\"Kind\" IN ('Explain', 'Example', 'Trap', 'LiveContext', 'Source')");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Education.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("PassingScore")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("Quizzes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Quizzes_PassingScore", "\"PassingScore\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Education.QuizOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "OrderIndex");

                    b.ToTable("QuizOptions", (string)null);
                });

            modelBuilder.Entity("Finans.Domain.Education.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId", "OrderIndex");

                    b.ToTable("QuizQuestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_QuizQuestions_Type", "\"Type\" IN ('SingleChoice', 'MultipleChoice', 'TrueFalse')");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Education.UserLessonProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "LessonId")
                        .IsUnique();

                    b.ToTable("UserLessonProgress", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserLessonProgress_Percent", "\"ProgressPercent\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_UserLessonProgress_Status", "\"Status\" IN ('NotStarted', 'InProgress', 'Completed')");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Education.UserQuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId", "QuizId");

                    b.ToTable("UserQuizAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserQuizAttempts_Score", "\"Score\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Identity.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasColumnType("text");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", null, t =>
                        {
                            t.HasCheckConstraint("CK_AuditLogs_Action", "\"Action\" IN ('Login', 'Logout', 'Create', 'Update', 'Delete', 'AccessDenied', 'Export', 'PasswordChange')");

                            t.HasCheckConstraint("CK_AuditLogs_Result", "\"Result\" IN ('Success', 'Denied', 'Failure')");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("CreatedByIp")
                        .HasColumnType("inet");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Finans.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Roles_Name", "\"Name\" IN ('User', 'Admin')");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("citext");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LiteracyLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProfiledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskAttitude")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_BaseCurrency", "\"BaseCurrency\" IN ('TRY', 'USD', 'EUR')");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Identity.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Exchange")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PricingCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Assets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assets_PricingCurrency", "\"PricingCurrency\" IN ('TRY', 'USD', 'EUR')");

                            t.HasCheckConstraint("CK_Assets_Type", "\"Type\" IN ('Gold', 'Fx', 'Stock', 'Fund', 'Bes', 'Cash')");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.BesContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HoldingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OwnAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("StateAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId", "PaidAtUtc")
                        .IsDescending(false, true);

                    b.ToTable("BesContributions", null, t =>
                        {
                            t.HasCheckConstraint("CK_BesContributions_Own", "\"OwnAmount\" >= 0");

                            t.HasCheckConstraint("CK_BesContributions_State", "\"StateAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.BesDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<int?>("ContributionDay")
                        .HasColumnType("integer");

                    b.Property<Guid>("HoldingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MonthlyAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("OwnContribution")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("PlanActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ProviderName")
                        .HasColumnType("text");

                    b.Property<decimal>("StateContribution")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("VestingState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId")
                        .IsUnique();

                    b.ToTable("BesDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_BesDetails_Own", "\"OwnContribution\" >= 0");

                            t.HasCheckConstraint("CK_BesDetails_State", "\"StateContribution\" >= 0");

                            t.HasCheckConstraint("CK_BesDetails_Vesting", "\"VestingState\" IN ('NotVested', 'PartiallyVested', 'Vested')");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.FxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AsOfUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("Id");

                    b.HasIndex("FromCurrency", "ToCurrency", "AsOfUtc")
                        .IsDescending(false, false, true);

                    b.ToTable("FxRates", null, t =>
                        {
                            t.HasCheckConstraint("CK_FxRates_From", "\"FromCurrency\" IN ('TRY', 'USD', 'EUR')");

                            t.HasCheckConstraint("CK_FxRates_Rate", "\"Rate\" > 0");

                            t.HasCheckConstraint("CK_FxRates_To", "\"ToCurrency\" IN ('TRY', 'USD', 'EUR')");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.Holding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvgCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AssetId")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Holdings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Holdings_AvgCost", "\"AvgCost\" >= 0");

                            t.HasCheckConstraint("CK_Holdings_Quantity", "\"Quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.InflationRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AnnualRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodStartUtc", "PeriodEndUtc");

                    b.ToTable("InflationRates", (string)null);
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.PriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AsOfUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "AsOfUtc")
                        .IsDescending(false, true);

                    b.ToTable("PriceSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_PriceSnapshots_Price", "\"Price\" >= 0");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("HoldingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("TransactedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("HoldingId", "TransactedAtUtc");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Fee", "\"Fee\" >= 0");

                            t.HasCheckConstraint("CK_Transactions_Quantity", "\"Quantity\" > 0");

                            t.HasCheckConstraint("CK_Transactions_Type", "\"Type\" IN ('Buy', 'Sell')");

                            t.HasCheckConstraint("CK_Transactions_UnitPrice", "\"UnitPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("Finans.Domain.Education.Lesson", b =>
                {
                    b.HasOne("Finans.Domain.Education.LearningTrack", "Track")
                        .WithMany("Lessons")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Finans.Domain.Education.LessonConceptTag", b =>
                {
                    b.HasOne("Finans.Domain.Education.ConceptTag", "ConceptTag")
                        .WithMany("Lessons")
                        .HasForeignKey("ConceptTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finans.Domain.Education.Lesson", "Lesson")
                        .WithMany("ConceptTags")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConceptTag");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Finans.Domain.Education.LessonPrerequisite", b =>
                {
                    b.HasOne("Finans.Domain.Education.Lesson", "Lesson")
                        .WithMany("Prerequisites")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finans.Domain.Education.Lesson", "PrerequisiteLesson")
                        .WithMany()
                        .HasForeignKey("PrerequisiteLessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("PrerequisiteLesson");
                });

            modelBuilder.Entity("Finans.Domain.Education.LessonSection", b =>
                {
                    b.HasOne("Finans.Domain.Education.Lesson", "Lesson")
                        .WithMany("Sections")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Finans.Domain.Education.Quiz", b =>
                {
                    b.HasOne("Finans.Domain.Education.Lesson", "Lesson")
                        .WithOne("Quiz")
                        .HasForeignKey("Finans.Domain.Education.Quiz", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Finans.Domain.Education.QuizOption", b =>
                {
                    b.HasOne("Finans.Domain.Education.QuizQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Finans.Domain.Education.QuizQuestion", b =>
                {
                    b.HasOne("Finans.Domain.Education.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Finans.Domain.Education.UserLessonProgress", b =>
                {
                    b.HasOne("Finans.Domain.Education.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finans.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finans.Domain.Education.UserQuizAttempt", b =>
                {
                    b.HasOne("Finans.Domain.Education.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finans.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finans.Domain.Identity.AuditLog", b =>
                {
                    b.HasOne("Finans.Domain.Identity.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finans.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("Finans.Domain.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finans.Domain.Identity.UserRoleAssignment", b =>
                {
                    b.HasOne("Finans.Domain.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finans.Domain.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.BesContribution", b =>
                {
                    b.HasOne("Finans.Domain.Portfolio.Holding", "Holding")
                        .WithMany("BesContributions")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.BesDetails", b =>
                {
                    b.HasOne("Finans.Domain.Portfolio.Holding", "Holding")
                        .WithOne("BesDetails")
                        .HasForeignKey("Finans.Domain.Portfolio.BesDetails", "HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.Holding", b =>
                {
                    b.HasOne("Finans.Domain.Portfolio.Asset", "Asset")
                        .WithMany("Holdings")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finans.Domain.Identity.User", "User")
                        .WithMany("Holdings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.PriceSnapshot", b =>
                {
                    b.HasOne("Finans.Domain.Portfolio.Asset", "Asset")
                        .WithMany("PriceSnapshots")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.Transaction", b =>
                {
                    b.HasOne("Finans.Domain.Portfolio.Holding", "Holding")
                        .WithMany("Transactions")
                        .HasForeignKey("HoldingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("Finans.Domain.Education.ConceptTag", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Finans.Domain.Education.LearningTrack", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Finans.Domain.Education.Lesson", b =>
                {
                    b.Navigation("ConceptTags");

                    b.Navigation("Prerequisites");

                    b.Navigation("Quiz");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Finans.Domain.Education.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Finans.Domain.Education.QuizQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Finans.Domain.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Finans.Domain.Identity.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Holdings");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.Asset", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("PriceSnapshots");
                });

            modelBuilder.Entity("Finans.Domain.Portfolio.Holding", b =>
                {
                    b.Navigation("BesContributions");

                    b.Navigation("BesDetails");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
